// เจ้าของไฟล์: คนที่ 2 (feature province)
// ข้อมูล mock ระดับจังหวัด (ยังไม่ต่อ backend) — เชียงใหม่เป็นจังหวัดตัวอย่าง

export const PROVINCES = [
  { id: 'cnx', name: 'เชียงใหม่' },
  { id: 'cri', name: 'เชียงราย' },
  { id: 'plk', name: 'พิษณุโลก' },
  { id: 'nma', name: 'นครราชสีมา' },
  { id: 'ubn', name: 'อุบลราชธานี' },
]

// KPI แถวบนสุดของภาพรวมจังหวัด
export const PROVINCE_KPIS = [
  {
    id: 'centers',
    label: 'ศูนย์ทั้งหมด',
    value: 57,
    unit: 'แห่ง',
    sub: 'เป้าหมาย 62 แห่ง (91.9%)',
    icon: 'Warehouse',
    tone: 'green',
  },
  {
    id: 'online',
    label: 'ศูนย์ออนไลน์',
    value: 52,
    unit: 'แห่ง',
    sub: 'คิดเป็น 91.2%',
    icon: 'Wifi',
    tone: 'teal',
  },
  {
    id: 'rice',
    label: 'ข้าวอบวันนี้',
    value: 1248.6,
    unit: 'ตัน',
    sub: 'เป้าหมาย 1,500 ตัน (83.2%)',
    icon: 'Wheat',
    tone: 'gold',
  },
  {
    id: 'awd',
    label: 'พื้นที่คาร์บอน (AWD)',
    value: 82645,
    unit: 'ไร่',
    sub: 'เป้าหมาย 90,000 ไร่ (91.8%)',
    icon: 'Leaf',
    tone: 'green',
  },
  {
    id: 'income',
    label: 'รายได้เกษตรกร',
    value: 12.68,
    unit: 'ล้านบาท',
    sub: '+18.4% จากเดือนก่อน',
    icon: 'Coins',
    tone: 'gold',
  },
  {
    id: 'register',
    label: 'ความคืบหน้าลงทะเบียน',
    value: 93.4,
    unit: '%',
    sub: 'สมาชิก 8,945 / 9,580 ราย',
    icon: 'ClipboardList',
    tone: 'teal',
  },
]

// สถานะศูนย์: ใช้ร่วมกันทุกหน้า
export const STATUS = {
  normal: { label: 'ปกติ', color: '#3fae57' },
  watch: { label: 'เฝ้าระวัง', color: '#e8b84b' },
  issue: { label: 'มีปัญหา', color: '#f0883e' },
  critical: { label: 'วิกฤต', color: '#e5484d' },
  offline: { label: 'ออฟไลน์', color: '#8a978d' },
}

// รายอำเภอ (13 อำเภอตัวอย่าง)
export const DISTRICTS = [
  {
    name: 'สันทราย',
    rice: 182.4,
    awd: 12640,
    income: 2.48,
    complete: 98,
    issues: 0,
    score: 95.6,
  },
  {
    name: 'หางดง',
    rice: 156.8,
    awd: 10285,
    income: 2.15,
    complete: 95,
    issues: 1,
    score: 92.1,
  },
  {
    name: 'สันป่าตอง',
    rice: 142.3,
    awd: 9450,
    income: 1.92,
    complete: 94,
    issues: 1,
    score: 90.3,
  },
  {
    name: 'สารภี',
    rice: 128.75,
    awd: 8560,
    income: 1.78,
    complete: 93,
    issues: 1,
    score: 88.7,
  },
  {
    name: 'แม่แตง',
    rice: 116.2,
    awd: 7890,
    income: 1.55,
    complete: 90,
    issues: 2,
    score: 84.2,
  },
  {
    name: 'พร้าว',
    rice: 95.6,
    awd: 6120,
    income: 1.28,
    complete: 88,
    issues: 2,
    score: 80.1,
  },
  {
    name: 'ฝาง',
    rice: 83.4,
    awd: 4860,
    income: 1.05,
    complete: 85,
    issues: 2,
    score: 76.3,
  },
  {
    name: 'แม่แจ่ม',
    rice: 62.1,
    awd: 4150,
    income: 0.82,
    complete: 80,
    issues: 2,
    score: 70.4,
  },
  {
    name: 'จอมทอง',
    rice: 58.3,
    awd: 3780,
    income: 0.74,
    complete: 78,
    issues: 3,
    score: 68.2,
  },
  {
    name: 'ดอยเต่า',
    rice: 45.2,
    awd: 2950,
    income: 0.61,
    complete: 76,
    issues: 3,
    score: 64.0,
  },
  {
    name: 'ไชยปราการ',
    rice: 38.6,
    awd: 2410,
    income: 0.49,
    complete: 75,
    issues: 3,
    score: 62.8,
  },
  {
    name: 'เชียงดาว',
    rice: 32.8,
    awd: 2050,
    income: 0.42,
    complete: 74,
    issues: 3,
    score: 60.5,
  },
  {
    name: 'อมก๋อย',
    rice: 25.05,
    awd: 1700,
    income: 0.3,
    complete: 62,
    issues: 4,
    score: 48.6,
  },
]

// ศูนย์ข้าวชุมชน (18 ศูนย์ตัวอย่าง) — lat,lng คือพิกัดจริงบนแผนที่ (mock ตำแหน่งรายอำเภอ)
export const CENTERS = [
  {
    id: 'RC6601001',
    name: 'ศูนย์ข้าวบ้านหนองหว้า',
    district: 'สันทราย',
    status: 'normal',
    members: 312,
    rice: 42.5,
    awd: 2140,
    carbon: 385,
    sync: '5 นาทีที่แล้ว',
    lat: 18.9,
    lng: 99.04,
  },
  {
    id: 'RC6601002',
    name: 'ศูนย์ข้าวบ้านป่าเหมือด',
    district: 'สันทราย',
    status: 'normal',
    members: 268,
    rice: 38.2,
    awd: 1890,
    carbon: 342,
    sync: '8 นาทีที่แล้ว',
    lat: 18.86,
    lng: 99.08,
  },
  {
    id: 'RC6601023',
    name: 'ศูนย์ข้าวบ้านสหกรณ์พร้าว',
    district: 'พร้าว',
    status: 'watch',
    members: 214,
    rice: 24.8,
    awd: 1420,
    carbon: 262,
    sync: '32 นาทีที่แล้ว',
    lat: 19.365,
    lng: 99.205,
  },
  {
    id: 'RC6602012',
    name: 'ศูนย์ข้าวแม่แจ่ม',
    district: 'แม่แจ่ม',
    status: 'critical',
    members: 186,
    rice: 0,
    awd: 1150,
    carbon: 208,
    sync: '2 วันที่แล้ว',
    issue: 'เครื่องอบขัดข้อง กระทบคิวอบข้าว 48 ตัน',
    lat: 18.49,
    lng: 98.36,
  },
  {
    id: 'RC6602019',
    name: 'ศูนย์ข้าวบ้านแม่สอย',
    district: 'จอมทอง',
    status: 'watch',
    members: 158,
    rice: 18.4,
    awd: 980,
    carbon: 176,
    sync: '18 นาทีที่แล้ว',
    issue: 'น้ำไม่เพียงพอรอบ AWD ถัดไป',
    lat: 18.33,
    lng: 98.68,
  },
  {
    id: 'RC6603015',
    name: 'ศูนย์ข้าวอมก๋อยพัฒนา',
    district: 'อมก๋อย',
    status: 'critical',
    members: 142,
    rice: 6.2,
    awd: 760,
    carbon: 138,
    sync: '26 ชม.ที่แล้ว',
    issue: 'เชื่อมต่อเซ็นเซอร์ไม่ได้ทั้งศูนย์',
    lat: 17.8,
    lng: 98.36,
  },
  {
    id: 'RC6603022',
    name: 'ศูนย์ข้าวบ้านยางเปียง',
    district: 'อมก๋อย',
    status: 'offline',
    members: 96,
    rice: 0,
    awd: 480,
    carbon: 84,
    sync: '3 วันที่แล้ว',
    issue: 'ออฟไลน์เกิน 24 ชม.',
    lat: 17.72,
    lng: 98.42,
  },
  {
    id: 'RC6604018',
    name: 'ศูนย์ข้าวฝางเหนือ',
    district: 'ฝาง',
    status: 'issue',
    members: 205,
    rice: 21.6,
    awd: 1260,
    carbon: 232,
    sync: '41 นาทีที่แล้ว',
    issue: 'ข้อมูลแปลงไม่ครบ 38 แปลง',
    lat: 19.92,
    lng: 99.21,
  },
  {
    id: 'RC6604021',
    name: 'ศูนย์ข้าวบ้านม่วงคำ',
    district: 'ฝาง',
    status: 'normal',
    members: 174,
    rice: 19.8,
    awd: 1080,
    carbon: 198,
    sync: '6 นาทีที่แล้ว',
    lat: 19.98,
    lng: 99.16,
  },
  {
    id: 'RC6605009',
    name: 'ศูนย์ข้าวหางดงรวมใจ',
    district: 'หางดง',
    status: 'normal',
    members: 296,
    rice: 40.6,
    awd: 2060,
    carbon: 371,
    sync: '3 นาทีที่แล้ว',
    lat: 18.69,
    lng: 98.92,
  },
  {
    id: 'RC6605011',
    name: 'ศูนย์ข้าวบ้านต้นแก้ว',
    district: 'หางดง',
    status: 'watch',
    members: 188,
    rice: 22.4,
    awd: 1240,
    carbon: 224,
    sync: '55 นาทีที่แล้ว',
    issue: 'เซ็นเซอร์ทำงานผิดปกติ 3 จุด',
    lat: 18.72,
    lng: 98.96,
  },
  {
    id: 'RC6606004',
    name: 'ศูนย์ข้าวสันป่าตองก้าวหน้า',
    district: 'สันป่าตอง',
    status: 'normal',
    members: 342,
    rice: 45.1,
    awd: 2350,
    carbon: 412,
    sync: '2 นาทีที่แล้ว',
    lat: 18.62,
    lng: 98.89,
  },
  {
    id: 'RC6607003',
    name: 'ศูนย์ข้าวสารภีศรีบุญเรือง',
    district: 'สารภี',
    status: 'normal',
    members: 254,
    rice: 36.9,
    awd: 1980,
    carbon: 356,
    sync: '4 นาทีที่แล้ว',
    lat: 18.71,
    lng: 99.04,
  },
  {
    id: 'RC6608007',
    name: 'ศูนย์ข้าวแม่แตงสามัคคี',
    district: 'แม่แตง',
    status: 'issue',
    members: 232,
    rice: 26.3,
    awd: 1520,
    carbon: 274,
    sync: '1 ชม.ที่แล้ว',
    issue: 'คิวอบข้าวล่าช้า 2 รอบ',
    lat: 19.11,
    lng: 98.94,
  },
  {
    id: 'RC6608010',
    name: 'ศูนย์ข้าวบ้านช่อแล',
    district: 'แม่แตง',
    status: 'normal',
    members: 178,
    rice: 20.7,
    awd: 1140,
    carbon: 208,
    sync: '9 นาทีที่แล้ว',
    lat: 19.05,
    lng: 99.0,
  },
  {
    id: 'RC6609002',
    name: 'ศูนย์ข้าวเชียงดาวพัฒนา',
    district: 'เชียงดาว',
    status: 'watch',
    members: 146,
    rice: 14.2,
    awd: 890,
    carbon: 162,
    sync: '47 นาทีที่แล้ว',
    issue: 'ความชื้นข้าวเปลือกสูงกว่าเกณฑ์',
    lat: 19.36,
    lng: 98.96,
  },
  {
    id: 'RC6610006',
    name: 'ศูนย์ข้าวดอยเต่ารุ่งเรือง',
    district: 'ดอยเต่า',
    status: 'offline',
    members: 118,
    rice: 0,
    awd: 620,
    carbon: 112,
    sync: '28 ชม.ที่แล้ว',
    issue: 'ออฟไลน์เกิน 24 ชม.',
    lat: 17.96,
    lng: 98.68,
  },
  {
    id: 'RC6611005',
    name: 'ศูนย์ข้าวไชยปราการรวมพลัง',
    district: 'ไชยปราการ',
    status: 'normal',
    members: 162,
    rice: 17.9,
    awd: 1010,
    carbon: 184,
    sync: '11 นาทีที่แล้ว',
    lat: 19.73,
    lng: 99.14,
  },
]

// การแจ้งเตือนของจังหวัด
export const INITIAL_ALERTS = [
  {
    id: 'a1',
    severity: 'critical',
    title: 'เครื่องอบขัดข้อง — ศูนย์ข้าวแม่แจ่ม (RC6602012)',
    detail:
      'เครื่องอบหยุดทำงาน 2 วัน กระทบคิวอบข้าว 48 ตัน แนะนำส่งเครื่องอบสำรองและทีมช่างด่วน',
    time: 'วันนี้ 08:52',
    district: 'แม่แจ่ม',
    read: false,
  },
  {
    id: 'a2',
    severity: 'critical',
    title: 'เชื่อมต่อเซ็นเซอร์ไม่ได้ — ศูนย์ข้าวอมก๋อยพัฒนา (RC6603015)',
    detail: 'เกตเวย์หลุดการเชื่อมต่อ 26 ชม. ข้อมูลน้ำ-ดินไม่เข้าระบบทั้งศูนย์',
    time: 'วันนี้ 07:40',
    district: 'อมก๋อย',
    read: false,
  },
  {
    id: 'a3',
    severity: 'warning',
    title: 'ศูนย์ออฟไลน์เกิน 24 ชม. 2 แห่ง',
    detail:
      'RC6603022 (อมก๋อย) และ RC6610006 (ดอยเต่า) ไม่ส่งข้อมูลเกิน 24 ชม.',
    time: 'วันนี้ 07:10',
    district: 'อมก๋อย / ดอยเต่า',
    read: false,
  },
  {
    id: 'a4',
    severity: 'warning',
    title: 'จุดความร้อน 18 จุด ในเขตพื้นที่เฝ้าระวังการเผา',
    detail:
      'พบจุดความร้อนรอบพื้นที่ อ.แม่แจ่ม และ อ.อมก๋อย ใน 24 ชม. โปรดประสานเครือข่ายงดเผาฟาง',
    time: 'วันนี้ 06:30',
    district: 'แม่แจ่ม / อมก๋อย',
    read: false,
  },
  {
    id: 'a5',
    severity: 'warning',
    title: 'น้ำไม่เพียงพอรอบ AWD — ศูนย์ข้าวบ้านแม่สอย (RC6602019)',
    detail: 'ปริมาณน้ำในคลองสาขาต่ำกว่า 20% ประสานชลประทานจัดรอบส่งน้ำเพิ่ม',
    time: 'เมื่อวาน 16:45',
    district: 'จอมทอง',
    read: true,
  },
  {
    id: 'a6',
    severity: 'info',
    title: 'ข้อมูลแปลงไม่ครบ — ศูนย์ข้าวฝางเหนือ (RC6604018)',
    detail: 'เหลือแปลงที่ยังไม่เก็บข้อมูล 38 แปลง จากเป้าหมายรอบนี้ 420 แปลง',
    time: 'เมื่อวาน 14:20',
    district: 'ฝาง',
    read: true,
  },
  {
    id: 'a7',
    severity: 'info',
    title: 'รายงานประจำเดือนจากศูนย์ รออนุมัติ 5 ฉบับ',
    detail:
      'มีรายงานผลการดำเนินงานเดือน พ.ค. จาก 5 ศูนย์ รอการตรวจสอบและอนุมัติ',
    time: 'เมื่อวาน 09:00',
    district: '-',
    read: true,
  },
]

// ความคืบหน้าโครงการ 5 ด้าน
export const PROGRESS_TRACKS = [
  {
    id: 'machine',
    label: 'ติดตั้งเครื่องจักร',
    done: 52,
    target: 57,
    unit: 'แห่ง',
    color: '#3fae57',
  },
  {
    id: 'member',
    label: 'ลงทะเบียนสมาชิก',
    done: 8945,
    target: 9580,
    unit: 'ราย',
    color: '#4aa8e0',
  },
  {
    id: 'plot',
    label: 'เก็บข้อมูลแปลง',
    done: 7865,
    target: 8940,
    unit: 'แปลง',
    color: '#8ec36b',
  },
  {
    id: 'baseline',
    label: 'Baseline คาร์บอน',
    done: 7310,
    target: 8940,
    unit: 'แปลง',
    color: '#e8b84b',
  },
  {
    id: 'sensor',
    label: 'เชื่อมต่อเซ็นเซอร์',
    done: 1260,
    target: 1470,
    unit: 'จุด',
    color: '#f0883e',
  },
]

// ความคืบหน้ารายอำเภอ (% ของแต่ละด้าน)
export const DISTRICT_PROGRESS = DISTRICTS.map((d, i) => ({
  name: d.name,
  machine: Math.min(100, Math.round(d.complete + 2 - i * 0.5)),
  member: Math.min(100, Math.round(d.complete + 1)),
  plot: Math.max(50, Math.round(d.complete - 4)),
  baseline: Math.max(45, Math.round(d.complete - 8)),
  sensor: Math.max(40, Math.round(d.complete - 6 - (i % 3) * 2)),
}))

// รายงานสรุปที่ออกได้
export const REPORT_TEMPLATES = [
  {
    id: 'monthly',
    name: 'รายงานผลการดำเนินงานประจำเดือน',
    desc: 'สรุปข้าวอบ สมาชิก รายได้ และปัญหาของทุกศูนย์ในจังหวัด',
    icon: 'FileBarChart',
  },
  {
    id: 'carbon',
    name: 'รายงานคาร์บอนและการไม่เผา',
    desc: 'พื้นที่ AWD, Baseline, จุดความร้อน และคาร์บอนเครดิตสะสม',
    icon: 'Leaf',
  },
  {
    id: 'water',
    name: 'รายงานการจัดการน้ำ',
    desc: 'รอบส่งน้ำ ระดับน้ำในคลอง และผลกระทบต่อรอบ AWD',
    icon: 'Droplets',
  },
  {
    id: 'machine',
    name: 'รายงานสถานะเครื่องจักรและ IoT',
    desc: 'ความพร้อมเครื่องอบ โซลาร์เซลล์ เซ็นเซอร์ และงานซ่อมค้าง',
    icon: 'Wrench',
  },
]

// รายงานจากศูนย์ที่รออนุมัติ
export const INITIAL_PENDING_REPORTS = [
  {
    id: 'r1',
    center: 'ศูนย์ข้าวบ้านหนองหว้า (RC6601001)',
    type: 'รายงานประจำเดือน พ.ค.',
    sent: '22 พ.ค. 2567',
    status: 'pending',
  },
  {
    id: 'r2',
    center: 'ศูนย์ข้าวหางดงรวมใจ (RC6605009)',
    type: 'รายงานประจำเดือน พ.ค.',
    sent: '22 พ.ค. 2567',
    status: 'pending',
  },
  {
    id: 'r3',
    center: 'ศูนย์ข้าวสันป่าตองก้าวหน้า (RC6606004)',
    type: 'รายงานคาร์บอนไตรมาส 2',
    sent: '21 พ.ค. 2567',
    status: 'pending',
  },
  {
    id: 'r4',
    center: 'ศูนย์ข้าวแม่แตงสามัคคี (RC6608007)',
    type: 'รายงานประจำเดือน พ.ค.',
    sent: '21 พ.ค. 2567',
    status: 'pending',
  },
  {
    id: 'r5',
    center: 'ศูนย์ข้าวไชยปราการรวมพลัง (RC6611005)',
    type: 'รายงานประจำเดือน พ.ค.',
    sent: '20 พ.ค. 2567',
    status: 'pending',
  },
]

// ประเด็นสำคัญจาก AI (แสดงบนภาพรวม)
export const AI_INSIGHTS = [
  {
    level: 'critical',
    title: 'อำเภออมก๋อย',
    detail:
      'ผลงานต่ำสุด ข้อมูลไม่ครบ 62% ศูนย์มีปัญหา 4 แห่ง — ควรส่งทีมสนับสนุนภายในสัปดาห์นี้',
  },
  {
    level: 'warning',
    title: 'อำเภอแม่แจ่ม',
    detail:
      'เสี่ยงขาดน้ำรอบต่อไป คาดผลผลิตต่ำกว่าปกติ 35% — ประสานชลประทานเพิ่มรอบส่งน้ำ',
  },
  {
    level: 'warning',
    title: 'ศูนย์ข้าวแม่แจ่ม (RC6602012)',
    detail:
      'เครื่องอบขัดข้อง 2 วัน กระทบคิวอบข้าว 48 ตัน — แนะนำจัดสรรเครื่องอบสำรอง 1 เครื่อง',
  },
]

export const AI_ACTIONS = [
  'เร่งทีมจัดเก็บข้อมูลแปลงในอมก๋อย',
  'สนับสนุนเครื่องอบสำรอง 1 เครื่อง ที่แม่แจ่ม',
  'ส่งทีมช่างตรวจเช็คศูนย์ปัญหาเร่งด่วน 5 แห่ง',
  'จัดอบรมสมาชิกเรื่อง AWD ในแม่แจ่ม',
]

// ตัวช่วยจัดรูปตัวเลข
export const fmt = (n, digits = 0) =>
  n.toLocaleString('th-TH', {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  })
